задачи createGetter, invertObj, trimSymbols и uniq
js-tasks-ru/js-20200928_agmironov pull request #3
Opened 2020-10-08 11:27 UTC by agmironov

задачи createGetter, invertObj, trimSymbols и uniq

2020-10-08 11:35 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
createGetter
+ should return existed properties
+ should return "undefined" for properties which does not exist
+ gets obj.property
+ returns undefined for no property
+ gets obj.nested.property
+ returns undefined for no nested.property
+ gets more.nested.property
```
```diff
trimSymbols
+ should remove an identical consecutive characters that exceed the specified size
+ should return empty string if it was passed to function like an argument
+ should return empty string if "size" equal 0
+ should return the same string if "size" parameter wasn't specified
```
```diff
invertObj
+ should swap keys and values and return new object
+ should return empty object if was passed object without values
+ should return "undefined" if object wasn't passed
```
```diff
uniq
+ should return array with uniq values
+ should return empty array if was passed array without values
+ should return empty array if arguments wasn't passed
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-10-09 19:36 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    return path.split('.')
было бы неплохо вынести `path.split('.')` в родительскую функцию, иначе данная операция будет выполняться каждый раз при вызове геттера, хотя данное значение требуется рассчитать только один раз при создании геттера

2020-10-09 19:37 UTC, dosandk requested changes
решения кроме `createGetter` принимаются, внесите изменения согласно комментам

2020-10-09 19:53 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-10-09 19:59 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-10-12 12:06 UTC, dosandk approved these changes

2020-10-12 12:07 UTC, merged